### ISSUE TITLE
Feature: More generic fromEvent

### ISSUE THREAD

**Issue by hoichi** [mostjs/dom-event#138]
I’m trying to use dom-event with Chokidar, because it’s the closest thing I’ve found to `fromEvent` from Most v.1. But there are two problems with it:
1. Chokidar watcher doesn’t have `addEventListener` method, only `addListener` and `on`.
2. It feels kinda silly to use something called `DOM event` for events that have nothing to do with DOM.

I could live with the second one, but can we do something about the first? For instance, customize the method that adds a listener to a “node”? Or is it outside of dom-event’s scope and it’s better to just copy `domEvent`	and create a separate fromEvent package?

**Comment by briancavalier** [comment]
Hi @hoichi.  Yes, I think it's best for `@most/dom-event` to stay focused on the DOM.  A [community package](https://github.com/mostjs-community) for Node event emitter support seems like a good way to go.  Would you be interested in creating one?

**Comment by hoichi** [comment]
I would. Where do I start? Should I begin with a repo owned by me? Is there a package with boilerplate I should model after?

**Comment by briancavalier** [comment]
Great, thank you!  Yes, you can absolutely start with your own repo.  See the [Getting Involved](https://github.com/mostjs-community/about#getting-involved) section for instructions to become a mostjs-community member.  Once you're a member, it's your choice on whether you'd like to transfer your repo into mostjs-community--either way, you still retain ownership.

We do have a [package-starter](https://github.com/mostjs/package-starter), you can use, although it's a bit out of date right now (sorry about that!).  If you have another package boilerplate that you'd like to use, that's fine too.  If possible, we'd prefer that the package publish both a UMD and ES module build in the same way that [`@most/dom-event`](https://github.com/mostjs/dom-event/blob/master/package.json#L5-L6) does, so that users can take advantage of tree-shaking.

And finally, feel free to join us in [gitter](https://gitter.im/cujojs/most).

I'll close this issue, but if you more questions about getting started, feel free to ask here or in gitter.
