### ISSUE TITLE
Feature Suggestion: Improve TypeScript Definitions

### ISSUE THREAD

**Issue by TylorS** [mostjs/dom-event#78]
We could improve the individual event types such as `click` by adjusting it to

```typescript
click(node: EventTarget, useCapture?: boolean): Stream<MouseEvent>;
```

This would avoid the need to do manual typecasting for users. 

It may also be possible to improve the typings of `domEvent` with at least a change to

```typescript
domEvent<T extends Event>(eventType: string, node: EventTarget, useCapture?: boolean): Stream<T>
```

but we may want to consider typing `eventType` with a union type of all of the standardized event types. I have an existing list of such types [here](https://github.com/motorcyclejs/motorcyclejs/blob/master/dom/src/types/Events.ts#L148).

**Comment by briancavalier** [comment]
> but we may want to consider typing eventType with a union type of all of the standardized event types

I like this idea.  My only concern with it is that it seems like it prevents using custom events.  I don't know how common custom events are in the wild, though.

Maybe the best first step is to tighten the types on the specific event functions, like `click`.

> It may also be possible to improve the typings of domEvent with at least a change to

I'm still not clear on how this works.  I know TS can't actually infer the concrete T, since it's only mentioned in the return type.  Can some tools, like VS Code determine T based on the type that is being demanded by an assignment or function argument?

For example, if one does (sorry if my TS syntax is wrong, but hopefully you get the idea!):

```js
const s = fromEvent('mousemove', window)
```

How will TS or related tools infer that T is MouseEvent?  Do you need to give TS some additional hint?

**Comment by TylorS** [comment]
> Can some tools, like VS Code determine T based on the type that is being demanded by an assignment or function argument

We can do it via overloading, but it's not super fun on our side.

```typescript
domEvent(eventType: 'click', node: EventTarget, useCapture?: boolean): Stream<MouseEvent>;
domEvent(eventType: 'touchstart', node: EventTarget, useCapture?: boolean): Stream<TouchEvent>;
// provide a fallback, for custom events
domEvent<T extends Event>(eventType: string, node: EventTarget, useCapture?: boolean): Stream<T>;
```

**Comment by briancavalier** [comment]
@TylorS Can we close this now that #141 has been merged & released?

**Comment by TylorS** [comment]
Yes, @briancavalier this has been addressed

**Comment by briancavalier** [comment]
Thanks!
